# Generated by Django 4.1.1 on 2023-03-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_ispockettransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.pocket')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
    ]
