# Generated by Django 4.1.1 on 2023-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_pockettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pockettransaction',
            name='pocket_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
