# Generated by Django 4.1.1 on 2023-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_pockettransaction_pocket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pockettransaction',
            name='pocket_description',
        ),
        migrations.AddField(
            model_name='pocket',
            name='pocket_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
