# Generated by Django 4.1.1 on 2023-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_balancestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancestatistics',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
